// This file is auto-generated by scripts/registry-tags/index.ts
// Do not edit this file directly.

// ---------- STATISTICS ----------
// Total components: 163
// Total tags: 352
// Unique tags: 58
// ------------------------------

// ---------- TAG USAGE ----------
// label: 75
// button: 65
// input: 56
// textarea: 19
// date: 8
// dropdown: 6
// counter: 6
// toggle group: 5
// checkout: 4
// payment: 4
// credit card: 4
// form: 4
// user: 4
// avatar: 4
// profile: 4
// social: 4
// login: 4
// authentication: 4
// disabled: 3
// search: 3
// calendar: 3
// picker: 3
// otp: 3
// mask: 3
// helper: 2
// hint: 2
// error: 2
// select: 2
// native select: 2
// password: 2
// kbd: 2
// number: 2
// character limit: 2
// range calendar: 2
// read-only: 2
// tag: 2
// back: 2
// next: 2
// loading: 2
// menu: 2
// vote: 2
// like: 2
// upload: 2
// image: 2
// file: 1
// phone: 1
// time: 1
// required: 1
// delete: 1
// tooltip: 1
// hamburger: 1
// toggle: 1
// volume: 1
// controls: 1
// copy: 1
// previous: 1
// collapsible: 1
// notification: 1
// -----------------------------

export const registryTags = [
	'authentication',
	'avatar',
	'back',
	'button',
	'calendar',
	'character limit',
	'checkout',
	'collapsible',
	'controls',
	'copy',
	'counter',
	'credit card',
	'date',
	'delete',
	'disabled',
	'dropdown',
	'error',
	'file',
	'form',
	'hamburger',
	'helper',
	'hint',
	'image',
	'input',
	'kbd',
	'label',
	'like',
	'loading',
	'login',
	'mask',
	'menu',
	'native select',
	'next',
	'notification',
	'number',
	'otp',
	'password',
	'payment',
	'phone',
	'picker',
	'previous',
	'profile',
	'range calendar',
	'read-only',
	'required',
	'search',
	'select',
	'social',
	'tag',
	'textarea',
	'time',
	'toggle',
	'toggle group',
	'tooltip',
	'upload',
	'user',
	'volume',
	'vote'
] as const;

export type RegistryTag = (typeof registryTags)[number];
