// This file is auto-generated by scripts/registry-tags/index.ts
// Do not edit this file directly.

// ---------- STATISTICS ----------
// Total components: 94
// Total tags: 193
// Unique tags: 30
// ------------------------------

// ---------- TAG USAGE ----------
// input: 58
// label: 58
// button: 10
// date: 8
// checkout: 5
// payment: 5
// credit card: 5
// form: 5
// search: 3
// calendar: 3
// picker: 3
// otp: 3
// mask: 3
// select: 2
// native select: 2
// password: 2
// number: 2
// character limit: 2
// range calendar: 2
// tag: 2
// helper: 1
// hint: 1
// error: 1
// disabled: 1
// kbd: 1
// file: 1
// phone: 1
// read-only: 1
// time: 1
// textarea: 1
// -----------------------------

export const registryTags = [
	'button',
	'calendar',
	'character limit',
	'checkout',
	'credit card',
	'date',
	'disabled',
	'error',
	'file',
	'form',
	'helper',
	'hint',
	'input',
	'kbd',
	'label',
	'mask',
	'native select',
	'number',
	'otp',
	'password',
	'payment',
	'phone',
	'picker',
	'range calendar',
	'read-only',
	'search',
	'select',
	'tag',
	'textarea',
	'time'
] as const;

export type RegistryTag = (typeof registryTags)[number];
