// This file is auto-generated by scripts/registry-tags/index.ts
// Do not edit this file directly.

// ---------- STATISTICS ----------
// Total components: 535
// Total tags: 1494
// Unique tags: 127
// ------------------------------

// ---------- TAG USAGE ----------
// bits ui: 222
// label: 193
// button: 82
// input: 59
// select: 53
// avatar: 36
// checkbox: 31
// user: 28
// slider: 27
// dropdown: 24
// profile: 24
// notification: 23
// radio: 22
// badge: 21
// chip: 21
// accordion: 20
// tabs: 20
// table: 20
// textarea: 19
// navbar, navigation: 19
// tooltip: 18
// switch: 18
// dialog: 18
// modal: 18
// native select: 17
// card: 15
// popover: 15
// pagination: 15
// alert: 14
// banner: 12
// avatar group: 12
// timeline: 12
// error: 10
// search: 10
// flag: 10
// vertical timeline: 10
// authentication: 9
// tanstack: 9
// disabled: 8
// date: 8
// counter: 8
// status: 8
// success: 8
// form: 8
// breadcrumb: 8
// vote: 7
// darkmode: 7
// rating: 7
// warning: 7
// info: 7
// login: 6
// collapsible: 6
// command: 6
// combobox: 6
// autocomplete: 6
// range slider: 6
// range: 6
// sort: 6
// time: 5
// toggle group: 5
// social: 5
// image: 5
// kbd: 4
// calendar: 4
// picker: 4
// delete: 4
// pricing: 4
// vertical tabs: 4
// helper: 3
// otp: 3
// mask: 3
// timezone: 3
// vertical slider: 3
// signup: 3
// feedback: 3
// hover card: 3
// filter: 3
// hint: 2
// password: 2
// number: 2
// character limit: 2
// range calendar: 2
// read-only: 2
// required: 2
// back: 2
// next: 2
// loading: 2
// menu: 2
// toggle: 2
// volume: 2
// controls: 2
// copy: 2
// like: 2
// upload: 2
// reset: 2
// cookies: 2
// gdpr: 2
// privacy: 2
// toast: 2
// sonner: 2
// newsletter: 2
// subscribe: 2
// alert dialog: 2
// sticky: 2
// resize: 2
// file: 1
// phone: 1
// hamburger: 1
// previous: 1
// tree: 1
// week: 1
// color: 1
// checkout: 1
// payment: 1
// multiselect: 1
// equalizer: 1
// countdown: 1
// sale: 1
// team: 1
// onboarding: 1
// chart: 1
// text editor: 1
// share: 1
// tour: 1
// tag: 1
// vertical table: 1
// drag and drop: 1
// -----------------------------

export const registryTags = [
	'accordion',
	'alert',
	'alert dialog',
	'authentication',
	'autocomplete',
	'avatar',
	'avatar group',
	'back',
	'badge',
	'banner',
	'bits ui',
	'breadcrumb',
	'button',
	'calendar',
	'card',
	'character limit',
	'chart',
	'checkbox',
	'checkout',
	'chip',
	'collapsible',
	'color',
	'combobox',
	'command',
	'controls',
	'cookies',
	'copy',
	'countdown',
	'counter',
	'darkmode',
	'date',
	'delete',
	'dialog',
	'disabled',
	'drag and drop',
	'dropdown',
	'equalizer',
	'error',
	'feedback',
	'file',
	'filter',
	'flag',
	'form',
	'gdpr',
	'hamburger',
	'helper',
	'hint',
	'hover card',
	'image',
	'info',
	'input',
	'kbd',
	'label',
	'like',
	'loading',
	'login',
	'mask',
	'menu',
	'modal',
	'multiselect',
	'native select',
	'navbar, navigation',
	'newsletter',
	'next',
	'notification',
	'number',
	'onboarding',
	'otp',
	'pagination',
	'password',
	'payment',
	'phone',
	'picker',
	'popover',
	'previous',
	'pricing',
	'privacy',
	'profile',
	'radio',
	'range',
	'range calendar',
	'range slider',
	'rating',
	'read-only',
	'required',
	'reset',
	'resize',
	'sale',
	'search',
	'select',
	'share',
	'signup',
	'slider',
	'social',
	'sonner',
	'sort',
	'status',
	'sticky',
	'subscribe',
	'success',
	'switch',
	'table',
	'tabs',
	'tag',
	'tanstack',
	'team',
	'text editor',
	'textarea',
	'time',
	'timeline',
	'timezone',
	'toast',
	'toggle',
	'toggle group',
	'tooltip',
	'tour',
	'tree',
	'upload',
	'user',
	'vertical slider',
	'vertical table',
	'vertical tabs',
	'vertical timeline',
	'volume',
	'vote',
	'warning',
	'week'
] as const;

export type RegistryTag = (typeof registryTags)[number];
