name: 🐛 Bug Report
description: Found a bug? Let us help you fix it!
title: 'bug: '
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug.

  - type: input
    id: component-id
    attributes:
      label: Component ID
      description: Which specific component? (e.g., input-01, button-02)
      placeholder: 'input-01'

  - type: textarea
    id: current-expected-behavior
    attributes:
      label: Current & Expected Behavior
      description: What's happening that shouldn't be?
      placeholder: 'When I click the button...'
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Help us find the bug
      value: |
        1. Go to '...'
        2. Click on '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages in the console?
      render: shell
