name: 🧩 Component Request
description: Have an idea for a new component? Let's build it!
title: 'component: '
labels: ['component']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new component! Let's make something awesome together.

        > [!NOTE]
        > This project is a copy of the original Origin UI, reimplemented in Svelte. New components should aim to match the original Origin UI's design and functionality.
  - type: textarea
    id: examples
    attributes:
      label: Examples & Inspiration
      description: Share links to similar components
      placeholder: |
        - Design inspiration: ...
        - Similar component: ...
