name: 💡 Feature Request
description: Got an idea to make Origin UI - Svelte better? Share it here!
title: 'feat: '
labels: ['enhancement']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping make Origin UI - Svelte better! Let's hear your idea.

        > [!NOTE]
        > This project is a copy of the original Origin UI, reimplemented in Svelte. New features should align with and complement the original Origin UI's functionality.

  - type: dropdown
    id: feature-type
    attributes:
      label: Feature Type
      description: What area would this improve?
      options:
        - Developer Experience
        - Component Enhancement
        - Documentation
        - Performance
        - Accessibility
        - Other
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Related Component
      description: Does this affect a specific component type?
      options:
        - Not Component Specific
        - Inputs
        - Buttons
        - Accordions
        - Alerts
        - Avatars
        - Badges
        - Banners
        - Checkboxes
        - Dialogs
        - Dropdowns
        - 'Hover Cards'
        - Notifications
        - Popovers
        - Radios
        - Sliders
        - Switches
        - Textareas
        - Tooltips
        - Base UI Components
    validations:
      required: true

  - type: textarea
    id: problem
    attributes:
      label: Current Limitation
      description: What's missing or could be better?
      placeholder: 'It would be great if...'
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How could we solve this?
      placeholder: 'We could...'
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Approaches
      description: Are there other ways to solve this?
      placeholder: 'Another way could be...'

  - type: textarea
    id: examples
    attributes:
      label: Examples & References
      description: Share any examples or references
      placeholder: |
        - Similar feature in other libraries: ...
        - Reference implementation: ...

  - type: markdown
    attributes:
      value: |
        > [!TIP]
        > Not sure if this is the right approach? Open a discussion first - we're happy to brainstorm together!
