/* eslint-disable no-console */
import type { RegistryItem } from '@shadcn-svelte/registry';

import fs from 'node:fs';
import path from 'node:path';

import registry from '../../registry.json' assert { type: 'json' };

const OUTPUT_PATH = path.resolve(process.cwd(), 'src/lib/registry/tags.ts');
const SCRIPT_PATH = 'scripts/registry-tags/index.ts';

function generateTagsFileContent(
	uniqueTags: string[],
	tagCounts: Record<string, number>,
	totalTags: number,
	totalComponents: number
): string {
	const header = `// This file is auto-generated by ${SCRIPT_PATH}
// Do not edit this file directly.

// ---------- STATISTICS ----------
// Total components: ${totalComponents}
// Total tags: ${totalTags}
// Unique tags: ${uniqueTags.length}
// ------------------------------`;

	const sortedTagCounts = Object.entries(tagCounts).sort(([, a], [, b]) => b - a);

	const stats = sortedTagCounts.map(([tag, count]) => `// ${tag}: ${count}`).join('\n');

	const tagList = uniqueTags.map((tag) => `	'${tag}'`).join(',\n');
	let content = '';
	content += `export const registryTags = [\n${tagList}\n] as const;\n\n`;
	content += `export type RegistryTag = (typeof registryTags)[number];\n`;

	return `${header}\n\n// ---------- TAG USAGE ----------\n${stats}\n// -----------------------------\n\n${content}`;
}

function getAllTags(): string[] {
	const tags = registry.items.flatMap((item: unknown) => {
		const registryItem = item as unknown as RegistryItem;
		return registryItem.meta?.tags ?? [];
	});
	return tags.filter(Boolean);
}

function getTagStatistics(tags: string[]): {
	tagCounts: Record<string, number>;
	uniqueTags: string[];
} {
	const uniqueTags = [...new Set(tags)].sort();
	const tagCounts = tags.reduce(
		(acc, tag) => {
			acc[tag] = (acc[tag] || 0) + 1;
			return acc;
		},
		{} as Record<string, number>
	);

	return { tagCounts, uniqueTags };
}

function main() {
	console.log('Generating registry tags...');

	const allTags = getAllTags();
	const { tagCounts, uniqueTags } = getTagStatistics(allTags);
	const fileContent = generateTagsFileContent(
		uniqueTags,
		tagCounts,
		allTags.length,
		registry.items.length
	);

	const dir = path.dirname(OUTPUT_PATH);
	if (!fs.existsSync(dir)) {
		fs.mkdirSync(dir, { recursive: true });
	}

	fs.writeFileSync(OUTPUT_PATH, fileContent, 'utf-8');

	console.log(`✅ Generated ${OUTPUT_PATH} with ${uniqueTags.length} unique tags.`);
	console.log(`📊 See the file header for detailed statistics.`);
}

main();
